name: Build ZMK Firmware with nRFMicro 1.4
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:2.5
    strategy:
      fail-fast: false
      matrix:
        include:
          - shield: lily58_left
            board: nrfmicro@1.4.0
          - shield: lily58_right
            board: nrfmicro@1.4.0
          - shield: sofle_left
            board: nrfmicro@1.4.0
          - shield: sofle_right
            board: nrfmicro@1.4.0
          - shield: sofle_left
            board: nrfmicro@1.4.1
          - shield: sofle_right
            board: nrfmicro@1.4.1
          - board: cyber60@B
            keymap: config/boards/arm/cyber60/cyber60.keymap

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true


      - name: Initialize workspace (west init)
        run: west init -l config
      - name: Update modules (west update)
        run: west update
      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export


      - name: Prepare variables
        id: variables
        run: |
          SHIELD_ARG=
          ARTIFACT_NAME="${{ matrix.board }}"

          if [ -n "${{ matrix.shield }}" ]; then
            SHIELD_ARG="-DSHIELD=${{ matrix.shield }}"
            ARTIFACT_NAME="${ARTIFACT_NAME}-${{ matrix.shield }}"
          fi

          if [ -n "${{ matrix.keymap }}" ]; then
            SHIELD_ARG="${SHIELD_ARG} -DKEYMAP_FILE=${GITHUB_WORKSPACE}/${{ matrix.keymap }}"
          fi

          ARTIFACT_NAME="${ARTIFACT_NAME}-zmk"

          echo ::set-output name=shield-arg::${SHIELD_ARG}
          echo ::set-output name=artifact-name::${ARTIFACT_NAME}


      - name: Build debug images (west build)
        run: west build -s zmk/app -p -b ${{ matrix.board }} -- ${{ steps.variables.outputs.shield-arg }}
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DCONFIG_ZMK_USB_LOGGING=y
      - name: Generated DTS file
        if: always()
        run: cat -n build/zephyr/*.dts.pre.tmp
      - name: Generated zephyr DTS file
        if: always()
        run: cat -n build/zephyr/zephyr.dts
      - name: Generated config file
        if: always()
        run: cat -n build/zephyr/include/generated/autoconf.h
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.variables.outputs.artifact-name }}-debug
          path: |
            build/zephyr/zmk.hex
            build/zephyr/zmk.uf2
        continue-on-error: true


      - name: Build release images (west build)
        run: west build -s zmk/app -p -b ${{ matrix.board }} -- ${{ steps.variables.outputs.shield-arg }}
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.variables.outputs.artifact-name }}
          path: |
            build/zephyr/zmk.hex
            build/zephyr/zmk.uf2
        continue-on-error: true

